# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ccbe80015b3754c5985d590384dc0c8dbf75385be5a304eebe8ecfbfbcf8f851093cbdd8eea6d5e0885b785cd44991c9aa6379b422042e34ff5597a29316697

test:
  secret_key_base: f3eca6f84339a514f8b51a58f85cb9cfc56e8e6665c4a9afe66d2ae3c0ab9fcfb0ac30b7942e3a846fcf0685295ea19d68a43b98722ccacdb33a4a21293744d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
